### ISSUE TITLE
[how-to] Install and use library

### ISSUE THREAD

**Issue by isFakeAccount** [games-directory/api-psn#1]
Maybe because I am new with ruby and I don't have much clue but when I try to install the package by running 

> bundle exec rake install --trace

I get this
```
C:\Users\distr\Downloads\api-psn>bundle exec rake install --trace
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:698:in `raw_load_rakefile'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
C:/Ruby30-x64/bin/rake:23:in `load'
C:/Ruby30-x64/bin/rake:23:in `<main>'
```

Can you help me out? All the StackOverflow answers say that I should be in the root directory. I am in the root directory of the git project. I looked at other Ruby libraries as an example. It seems you might need to provide rakefile.rb

**Comment by pacMakaveli** [comment]
Sorry, the documentation provided in the read me is the generated one by bundler.

To install the dependencies you need to run ‘bundle install’ and then ‘bin/console’ to start testing it.
Haven’t tried this on windows but it should work. Let me know how it goes.

I’ll try and provide a quick and dirty how-to tomorrow for using this library.

**Comment by pacMakaveli** [comment]
The gem is heavily used in https://github.com/games-directory/games.directory/tree/develop/app/services/network/psn , so if you need any examples, refer to that repo while I sort out the proper documentation.

To obtain an NPSSO token, make sure you're logged in on your play station account and then visit: https://ca.account.sony.com/api/v1/ssocookie

To authenticate run `PlayStationNetworkAPI::Session.new(npsso).authenticate`
This will give a refresh_token which will expire in about 2 months. You'll need this for every request in order to obtain the `access_token`

```
api = PlayStationNetworkAPI::Client.new(refresh_token)

profile = api.user.profile
games =  api.game.games(offset: 0, limit: 10)
trophies = api.trophy.titles(offset: 0, limit: 10)
```

**Comment by isFakeAccount** [comment]
Thank you for responding. I was able to install and get it working. My lack of understanding of Ruby as language got in the way. 

Anyways I would definitely love to contribute to this project and if you allow I can port this project to python(something I am more familiar with).

To install the library I just followed these steps [How to install gem from GitHub source?
](https://stackoverflow.com/questions/2577346/how-to-install-gem-from-github-source). I feel silly for creating an issue. Anyways great project. :)

**Comment by pacMakaveli** [comment]
> Thank you for responding. I was able to install and get it working. My lack of understanding of Ruby got in the way. 
> 
> 
> 
> I would definitely love to contribute to this project and if you allow I can port this project to python (something I am more familiar with).
> 
> 
> 
> To install the library I just followed these steps [How to install gem from GitHub source?
> 
> ](https://stackoverflow.com/questions/2577346/how-to-install-gem-from-github-source) I feel silly for creating an issue. Anyways great project. :)

You're more than welcome to port it! The more languages available the better.

**Comment by rbhowsden** [comment]
Arrived here from the psn-php repo - while I don't have substantial Ruby experience, being able to translate the Ruby code is 10x easier than the PHP version.  Thanks for this. :)

@isFakeAccount - I'm thinking the same as you, wanting to port this over to Python. Hoping to get started this weekend, will keep updated.

**Comment by pacMakaveli** [comment]
@rbhowsden happy to hear that! Feel free to join the Postman workspace. I will update it with all the available routes, so you're not constricted by language.
https://www.getpostman.com/collections/bd86917d218e8a361903
